ol_sendInfo('Initializing Variables');
ol_runBlockingSubClient('incuctance','getdp inductor/inductor.pro -pre -msh inductor/inductor.msh');
e1.name  = 'rl/e1';
e1.type  = 'number';
e1.value = 0.0;
e1.label = 'e_1[V]';
e1.help  = 'Voltage 1';
ol_setParameter(e1);
e2.name  = 'rl/e2';
e2.type  = 'number';
e2.value = 0.0;
e2.label = 'e_2[V]';
e2.help  = 'Voltage 2';
ol_setParameter(e2);
tmax.name  = 'rl/tmax';
tmax.type  = 'number';
tmax.value = 0.001;
tmax.label = 'tmax[s]';
tmax.help  = 'Duration of the simulation';
ol_setParameter(tmax);
t.name  = 'rl/t';
t.type  = 'number';
t.value = 0.0;
t.label = 't[s]';
t.help  = 'Simulation time';
ol_setParameter(t);
